### ISSUE TITLE
学校启用了动态令牌验证，无法连接代理

### ISSUE THREAD

**Issue by OliverGrace** [SoraShu/easyconn-socks5-for-HITsz#1]
学校的验证是easyconnect登录验证网页之后网页会弹出动态令牌的输入框，验证通过后才能连接

**Comment by efJerryYang** [comment]
我认为一个可行的解决方案是使用 GUI 工具连接到代理服务器，例如使用 VNC Viewer，在 b 站上的 [这个视频](https://www.bilibili.com/video/BV163411Z7BD) 9分钟处看到了相关的介绍
